(function(window) {
  const algeriaData = [
    {
        "id": 1,
        "code": "01",
        "name": "Adrar",
        "communes": [
            "Adrar",
            "Akabli",
            "Aoulef",
            "Bouda",
            "Fenoughil",
            "In Zghmir",
            "Ouled Ahmed Timmi",
            "Reggane",
            "Sali",
            "Sebaa",
            "Tamantit",
            "Tamest",
            "Timekten",
            "Tit",
            "Tsabit",
            "Zaouiet Kounta"
        ]
    },
    {
        "id": 2,
        "code": "02",
        "name": "Chlef",
        "communes": [
            "Abou El Hassane",
            "Ain Merane",
            "Benairia",
            "Beni  Bouattab",
            "Beni Haoua",
            "Beni Rached",
            "Boukadir",
            "Bouzeghaia",
            "Breira",
            "Chettia",
            "Chlef",
            "Dahra",
            "El Hadjadj",
            "El Karimia",
            "El Marsa",
            "Harchoun",
            "Herenfa",
            "Labiod Medjadja",
            "Moussadek",
            "Oued Fodda",
            "Oued Goussine",
            "Oued Sly",
            "Ouled Abbes",
            "Ouled Ben Abdelkader",
            "Ouled Fares",
            "Oum Drou",
            "Sendjas",
            "Sidi Abderrahmane",
            "Sidi Akkacha",
            "Sobha",
            "Tadjena",
            "Talassa",
            "Taougrit",
            "Tenes",
            "Zeboudja"
        ]
    },
    {
        "id": 3,
        "code": "03",
        "name": "Laghouat",
        "communes": [
            "Ain Madhi",
            "Benacer Benchohra",
            "El Assafia",
            "El Haouaita",
            "Hassi Delaa",
            "Hassi R'mel",
            "Kheneg",
            "Ksar El Hirane",
            "Laghouat",
            "Sidi Makhlouf",
            "Tadjemout",
            "Tadjrouna"
        ]
    },
    {
        "id": 4,
        "code": "04",
        "name": "Oum El Bouaghi",
        "communes": [
            "Ain Babouche",
            "Ain Beida",
            "Ain Diss",
            "Ain Fekroun",
            "Ain Kercha",
            "Ain M'lila",
            "Ain Zitoun",
            "Behir Chergui",
            "Berriche",
            "Bir Chouhada",
            "Dhalaa",
            "El Amiria",
            "El Belala",
            "El Djazia",
            "El Fedjoudj Boughrara Sa",
            "El Harmilia",
            "Fkirina",
            "Hanchir Toumghani",
            "Ksar Sbahi",
            "Meskiana",
            "Oued Nini",
            "Ouled Gacem",
            "Ouled Hamla",
            "Ouled Zouai",
            "Oum El Bouaghi",
            "Rahia",
            "Sigus",
            "Souk Naamane",
            "Zorg"
        ]
    },
    {
        "id": 5,
        "code": "05",
        "name": "Batna",
        "communes": [
            "Ain Djasser",
            "Ain Touta",
            "Ain Yagout",
            "Arris",
            "Batna",
            "Beni Foudhala El Hakania",
            "Boulhilat",
            "Boumagueur",
            "Boumia",
            "Bouzina",
            "Chemora",
            "Chir",
            "Djerma",
            "El Hassi",
            "El Madher",
            "Fesdis",
            "Foum Toub",
            "Ghassira",
            "Gosbat",
            "Guigba",
            "Hidoussa",
            "Ichemoul",
            "Inoughissen",
            "Kimmel",
            "Ksar Bellezma",
            "Larbaa",
            "Lazrou",
            "Lemcene",
            "Maafa",
            "Menaa",
            "Merouana",
            "N Gaous",
            "Oued Chaaba",
            "Oued El Ma",
            "Oued Taga",
            "Ouled Aouf",
            "Ouled Fadel",
            "Ouled Sellem",
            "Ouled Si Slimane",
            "Ouyoun El Assafir",
            "Rahbat",
            "Ras El Aioun",
            "Sefiane",
            "Seriana",
            "T Kout",
            "Talkhamt",
            "Taxlent",
            "Tazoult",
            "Teniet El Abed",
            "Tighanimine",
            "Tigharghar",
            "Timgad",
            "Zanet El Beida"
        ]
    },
    {
        "id": 6,
        "code": "06",
        "name": "Bejaia",
        "communes": [
            "Adekar",
            "Ait R'zine",
            "Ait-Smail",
            "Akbou",
            "Akfadou",
            "Amalou",
            "Amizour",
            "Aokas",
            "Barbacha",
            "Bejaia",
            "Beni Djellil",
            "Beni K'sila",
            "Beni-Mallikeche",
            "Benimaouche",
            "Boudjellil",
            "Bouhamza",
            "Boukhelifa",
            "Chellata",
            "Chemini",
            "Darguina",
            "Dra El Caid",
            "El Kseur",
            "Fenaia Il Maten",
            "Feraoun",
            "Ighil-Ali",
            "Ighram",
            "Kendira",
            "Kherrata",
            "Leflaye",
            "M'cisna",
            "Melbou",
            "Oued Ghir",
            "Ouzellaguen",
            "Seddouk",
            "Sidi Ayad",
            "Sidi-Aich",
            "Smaoun",
            "Souk El Tenine",
            "Souk Oufella",
            "Tala Hamza",
            "Tamokra",
            "Tamridjet",
            "Taourit Ighil",
            "Taskriout",
            "Tazmalt",
            "Tibane",
            "Tichy",
            "Tifra",
            "Timezrit",
            "Tinebdar",
            "Tizi-N'berber",
            "Toudja"
        ]
    },
    {
        "id": 7,
        "code": "07",
        "name": "Biskra",
        "communes": [
            "Ain Naga",
            "Biskra",
            "Bordj Ben Azzouz",
            "Bouchakroun",
            "Chetma",
            "El Feidh",
            "El Ghrous",
            "El Hadjab",
            "El Haouch",
            "Foughala",
            "Khenguet Sidi Nadji",
            "Lichana",
            "Lioua",
            "M'chouneche",
            "M'lili",
            "Mekhadma",
            "Meziraa",
            "Oumache",
            "Ourlal",
            "Sidi Okba",
            "Tolga",
            "Zeribet El Oued"
        ]
    },
    {
        "id": 8,
        "code": "08",
        "name": "Bechar",
        "communes": [
            "Abadla",
            "Bechar",
            "Beni-Ounif",
            "Boukais",
            "Erg-Ferradj",
            "Kenadsa",
            "Lahmar",
            "Machraa-Houari-Boumediene",
            "Meridja",
            "Mogheul",
            "Tabelbala",
            "Taghit"
        ]
    },
    {
        "id": 9,
        "code": "09",
        "name": "Blida",
        "communes": [
            "Ain Romana",
            "Beni Mered",
            "Beni-Tamou",
            "Benkhelil",
            "Blida",
            "Bouarfa",
            "Boufarik",
            "Bougara",
            "Bouinan",
            "Chebli",
            "Chiffa",
            "Chrea",
            "Djebabra",
            "El-Affroun",
            "Guerrouaou",
            "Hammam Elouane",
            "Larbaa",
            "Meftah",
            "Mouzaia",
            "Oued  Djer",
            "Oued El Alleug",
            "Ouled Slama",
            "Ouled Yaich",
            "Souhane",
            "Soumaa"
        ]
    },
    {
        "id": 10,
        "code": "10",
        "name": "Bouira",
        "communes": [
            "Aghbalou",
            "Ahl El Ksar",
            "Ain El Hadjar",
            "Ain Laloui",
            "Ain Turk",
            "Ain-Bessem",
            "Ait Laaziz",
            "Aomar",
            "Ath Mansour",
            "Bechloul",
            "Bir Ghbalou",
            "Bordj Okhriss",
            "Bouderbala",
            "Bouira",
            "Boukram",
            "Chorfa",
            "Dechmia",
            "Dirah",
            "Djebahia",
            "El Adjiba",
            "El Asnam",
            "El Hachimia",
            "El Khabouzia",
            "El-Hakimia",
            "El-Mokrani",
            "Guerrouma",
            "Hadjera Zerga",
            "Haizer",
            "Hanif",
            "Kadiria",
            "Lakhdaria",
            "M Chedallah",
            "Maala",
            "Maamora",
            "Mezdour",
            "Oued El Berdi",
            "Ouled Rached",
            "Raouraoua",
            "Ridane",
            "Saharidj",
            "Souk El Khemis",
            "Sour El Ghozlane",
            "Taghzout",
            "Taguedite",
            "Z'barbar (El Isseri )"
        ]
    },
    {
        "id": 11,
        "code": "11",
        "name": "Tamanrasset",
        "communes": [
            "Abelsa",
            "Ain Amguel",
            "Idles",
            "Tamanrasset",
            "Tazrouk"
        ]
    },
    {
        "id": 12,
        "code": "12",
        "name": "Tebessa",
        "communes": [
            "Ain Zerga",
            "Bedjene",
            "Bekkaria",
            "Bir Dheheb",
            "Bir Mokkadem",
            "Boukhadra",
            "Boulhaf Dyr",
            "Cheria",
            "El Kouif",
            "El Malabiod",
            "El Meridj",
            "El Mezeraa",
            "El Ogla",
            "El-Aouinet",
            "El-Houidjbet",
            "Guorriguer",
            "Hammamet",
            "Morsott",
            "Ouenza",
            "Oum Ali",
            "Saf Saf El Ouesra",
            "Stah Guentis",
            "Tebessa",
            "Telidjen"
        ]
    },
    {
        "id": 13,
        "code": "13",
        "name": "Tlemcen",
        "communes": [
            "Ain Fetah",
            "Ain Fezza",
            "Ain Ghoraba",
            "Ain Kebira",
            "Ain Nehala",
            "Ain Tellout",
            "Ain Youcef",
            "Amieur",
            "Azail",
            "Bab El Assa",
            "Beni Bahdel",
            "Beni Boussaid",
            "Beni Khellad",
            "Beni Mester",
            "Beni Ouarsous",
            "Beni Smiel",
            "Beni Snous",
            "Bensekrane",
            "Bouhlou",
            "Chetouane",
            "Dar Yaghmoracen",
            "Djebala",
            "El Fehoul",
            "Fellaoucene",
            "Ghazaouet",
            "Hammam Boughrara",
            "Hennaya",
            "Honnaine",
            "M'sirda Fouaga",
            "Maghnia",
            "Mansourah",
            "Marsa Ben M'hidi",
            "Nedroma",
            "Oued Lakhdar",
            "Ouled Mimoun",
            "Ouled Riyah",
            "Remchi",
            "Sabra",
            "Sebbaa Chioukh",
            "Sebdou",
            "Sidi Abdelli",
            "Sidi Medjahed",
            "Souahlia",
            "Souani",
            "Souk Tleta",
            "Terny Beni Hediel",
            "Tianet",
            "Tlemcen",
            "Zenata"
        ]
    },
    {
        "id": 14,
        "code": "14",
        "name": "Tiaret",
        "communes": [
            "Ain Bouchekif",
            "Ain Deheb",
            "Ain Dzarit",
            "Ain El Hadid",
            "Ain Kermes",
            "Chehaima",
            "Dahmouni",
            "Djebilet Rosfa",
            "Djillali Ben Amar",
            "Faidja",
            "Frenda",
            "Guertoufa",
            "Madna",
            "Mahdia",
            "Mechraa Safa",
            "Medrissa",
            "Medroussa",
            "Meghila",
            "Mellakou",
            "Nadorah",
            "Naima",
            "Oued Lilli",
            "Rahouia",
            "Sebaine",
            "Sebt",
            "Si Abdelghani",
            "Sidi Abderrahmane",
            "Sidi Ali Mellal",
            "Sidi Bakhti",
            "Sidi Hosni",
            "Sougueur",
            "Tagdempt",
            "Takhemaret",
            "Tiaret",
            "Tidda",
            "Tousnina"
        ]
    },
    {
        "id": 15,
        "code": "15",
        "name": "Tizi Ouzou",
        "communes": [
            "Abi-Youcef",
            "Aghribs",
            "Agouni-Gueghrane",
            "Ain-El-Hammam",
            "Ain-Zaouia",
            "Ait Aggouacha",
            "Ait Bouaddou",
            "Ait Boumahdi",
            "Ait Khellili",
            "Ait Yahia Moussa",
            "Ait-Aissa-Mimoun",
            "Ait-Chafaa",
            "Ait-Mahmoud",
            "Ait-Oumalou",
            "Ait-Toudert",
            "Ait-Yahia",
            "Akbil",
            "Akerrou",
            "Assi-Youcef",
            "Azazga",
            "Azeffoun",
            "Beni Zmenzer",
            "Beni-Aissi",
            "Beni-Douala",
            "Beni-Yenni",
            "Beni-Zikki",
            "Boghni",
            "Boudjima",
            "Bounouh",
            "Bouzeguene",
            "Draa-Ben-Khedda",
            "Draa-El-Mizan",
            "Freha",
            "Frikat",
            "Iboudrarene",
            "Idjeur",
            "Iferhounene",
            "Ifigha",
            "Iflissen",
            "Illilten",
            "Illoula Oumalou",
            "Imsouhal",
            "Irdjen",
            "Larbaa Nath Irathen",
            "M'kira",
            "Maatkas",
            "Makouda",
            "Mechtras",
            "Mekla",
            "Mizrana",
            "Ouacif",
            "Ouadhias",
            "Ouaguenoun",
            "Sidi Namane",
            "Souama",
            "Souk-El-Tenine",
            "Tadmait",
            "Tigzirt",
            "Timizart",
            "Tirmitine",
            "Tizi N'tleta",
            "Tizi-Gheniff",
            "Tizi-Ouzou",
            "Tizi-Rached",
            "Yakourene",
            "Yatafene",
            "Zekri"
        ]
    },
    {
        "id": 16,
        "code": "16",
        "name": "Alger",
        "communes": [
            "Ain Benian",
            "Ain Taya",
            "Alger Centre",
            "Bab El Oued",
            "Bab Ezzouar",
            "Baba Hassen",
            "Bachedjerah",
            "Baraki",
            "Ben Aknoun",
            "Beni Messous",
            "Bir Mourad Rais",
            "Bir Touta",
            "Birkhadem",
            "Bologhine Ibnou Ziri",
            "Bordj El Bahri",
            "Bordj El Kiffan",
            "Bourouba",
            "Bouzareah",
            "Casbah",
            "Cheraga",
            "Dar El Beida",
            "Dely Ibrahim",
            "Djasr Kasentina",
            "Douira",
            "Draria",
            "El Achour",
            "El Biar",
            "El Harrach",
            "El Madania",
            "El Magharia",
            "El Marsa",
            "El Mouradia",
            "Hammamet",
            "Herraoua",
            "Hussein Dey",
            "Hydra",
            "Khraissia",
            "Kouba",
            "Les Eucalyptus",
            "Maalma",
            "Mohamed Belouzdad",
            "Mohammadia",
            "Oued Koriche",
            "Oued Smar",
            "Ouled Chebel",
            "Ouled Fayet",
            "Rahmania",
            "Rais Hamidou",
            "Reghaia",
            "Rouiba",
            "Sehaoula",
            "Sidi M'hamed",
            "Sidi Moussa",
            "Souidania",
            "Staoueli",
            "Tessala El Merdja",
            "Zeralda"
        ]
    },
    {
        "id": 17,
        "code": "17",
        "name": "Djelfa",
        "communes": [
            "Ain Chouhada",
            "Ain El Ibel",
            "Ain Maabed",
            "Benyagoub",
            "Charef",
            "Dar Chioukh",
            "Djelfa",
            "Douis",
            "El Guedid",
            "El Idrissia",
            "Hassi Bahbah",
            "Hassi El Euch",
            "M'liliha",
            "Moudjebara",
            "Sidi Baizid",
            "Taadmit",
            "Zaafrane",
            "Zaccar"
        ]
    },
    {
        "id": 18,
        "code": "18",
        "name": "Jijel",
        "communes": [
            "Bordj T'har",
            "Boudria Beniyadjis",
            "Bouraoui Belhadef",
            "Boussif Ouled Askeur",
            "Chahna",
            "Chekfa",
            "Djemaa Beni Habibi",
            "Djimla",
            "El Ancer",
            "El Aouana",
            "El Kennar Nouchfi",
            "El Milia",
            "Emir Abdelkader",
            "Erraguene Souissi",
            "Ghebala",
            "Jijel",
            "Kaous",
            "Khiri Oued Adjoul",
            "Oudjana",
            "Ouled Rabah",
            "Ouled Yahia Khadrouch",
            "Selma Benziada",
            "Settara",
            "Sidi Abdelaziz",
            "Sidi Marouf",
            "Taher",
            "Texenna",
            "Ziama Mansouriah"
        ]
    },
    {
        "id": 19,
        "code": "19",
        "name": "Setif",
        "communes": [
            "Ain Abessa",
            "Ain Arnat",
            "Ain Azel",
            "Ain El Kebira",
            "Ain Lahdjar",
            "Ain Oulmene",
            "Ain-Legradj",
            "Ain-Roua",
            "Ain-Sebt",
            "Ait Naoual Mezada",
            "Ait-Tizi",
            "Amoucha",
            "Babor",
            "Bazer-Sakra",
            "Beidha Bordj",
            "Bellaa",
            "Beni Chebana",
            "Beni Fouda",
            "Beni Ourtilane",
            "Beni Oussine",
            "Beni-Aziz",
            "Beni-Mouhli",
            "Bir Haddada",
            "Bir-El-Arch",
            "Bouandas",
            "Bougaa",
            "Bousselam",
            "Boutaleb",
            "Dehamcha",
            "Djemila",
            "Draa-Kebila",
            "El Eulma",
            "El Ouricia",
            "El-Ouldja",
            "Guellal",
            "Guelta Zerka",
            "Guenzet",
            "Guidjel",
            "Hamam Soukhna",
            "Hamma",
            "Hammam Guergour",
            "Harbil",
            "Kasr El Abtal",
            "Maaouia",
            "Maouaklane",
            "Mezloug",
            "Oued El Bared",
            "Ouled Addouane",
            "Ouled Sabor",
            "Ouled Si Ahmed",
            "Ouled Tebben",
            "Rosfa",
            "Salah Bey",
            "Serdj-El-Ghoul",
            "Setif",
            "Tachouda",
            "Tala-Ifacene",
            "Taya",
            "Tella",
            "Tizi N'bechar"
        ]
    },
    {
        "id": 20,
        "code": "20",
        "name": "Saida",
        "communes": [
            "Ain El Hadjar",
            "Ain Sekhouna",
            "Ain Soltane",
            "Doui Thabet",
            "El Hassasna",
            "Hounet",
            "Maamora",
            "Moulay Larbi",
            "Ouled Brahim",
            "Ouled Khaled",
            "Saida",
            "Sidi Ahmed",
            "Sidi Amar",
            "Sidi Boubekeur",
            "Tircine",
            "Youb"
        ]
    },
    {
        "id": 21,
        "code": "21",
        "name": "Skikda",
        "communes": [
            "Ain Bouziane",
            "Ain Charchar",
            "Ain Kechra",
            "Ain Zouit",
            "Azzaba",
            "Bekkouche Lakhdar",
            "Ben Azzouz",
            "Beni Bechir",
            "Beni Oulbane",
            "Beni Zid",
            "Bin El Ouiden",
            "Bouchetata",
            "Cheraia",
            "Collo",
            "Djendel Saadi Mohamed",
            "El Arrouch",
            "El Ghedir",
            "El Hadaiek",
            "El Marsa",
            "Emjez Edchich",
            "Es Sebt",
            "Filfila",
            "Hammadi Krouma",
            "Kanoua",
            "Kerkara",
            "Khenag Maoune",
            "Oued Zhour",
            "Ouldja Boulbalout",
            "Ouled Attia",
            "Ouled Habbaba",
            "Oum Toub",
            "Ramdane Djamel",
            "Salah Bouchaour",
            "Sidi Mezghiche",
            "Skikda",
            "Tamalous",
            "Zerdezas",
            "Zitouna"
        ]
    },
    {
        "id": 22,
        "code": "22",
        "name": "Sidi Bel Abbes",
        "communes": [
            "Ain El Berd",
            "Ain Kada",
            "Ain Thrid",
            "Ain Tindamine",
            "Ain- Adden",
            "Amarnas",
            "Bedrabine El Mokrani",
            "Belarbi",
            "Ben Badis",
            "Benachiba Chelia",
            "Bir El Hammam",
            "Boudjebaa El Bordj",
            "Boukhanefis",
            "Chetouane Belaila",
            "Dhaya",
            "El Hacaiba",
            "Hassi Dahou",
            "Hassi Zahana",
            "Lamtar",
            "M'cid",
            "Makedra",
            "Marhoum",
            "Merine",
            "Mezaourou",
            "Mostefa  Ben Brahim",
            "Moulay Slissen",
            "Oued Sebaa",
            "Oued Sefioun",
            "Oued Taourira",
            "Ras El Ma",
            "Redjem Demouche",
            "Sehala Thaoura",
            "Sfisef",
            "Sidi Ali Benyoub",
            "Sidi Ali Boussidi",
            "Sidi Bel-Abbes",
            "Sidi Brahim",
            "Sidi Chaib",
            "Sidi Dahou Zairs",
            "Sidi Hamadouche",
            "Sidi Khaled",
            "Sidi Lahcene",
            "Sidi Yacoub",
            "Tabia",
            "Taoudmout",
            "Tefessour",
            "Teghalimet",
            "Telagh",
            "Tenira",
            "Tessala",
            "Tilmouni",
            "Zerouala"
        ]
    },
    {
        "id": 23,
        "code": "23",
        "name": "Annaba",
        "communes": [
            "Ain El Berda",
            "Annaba",
            "Berrahal",
            "Chetaibi",
            "Cheurfa",
            "El Bouni",
            "El Eulma",
            "El Hadjar",
            "Oued El Aneb",
            "Seraidi",
            "Sidi Amar",
            "Treat"
        ]
    },
    {
        "id": 24,
        "code": "24",
        "name": "Guelma",
        "communes": [
            "Ain Ben Beida",
            "Ain Larbi",
            "Ain Makhlouf",
            "Ain Regada",
            "Ain Sandel",
            "Belkheir",
            "Bendjarah",
            "Beni Mezline",
            "Bordj Sabath",
            "Bou Hachana",
            "Bou Hamdane",
            "Bouati Mahmoud",
            "Bouchegouf",
            "Boumahra Ahmed",
            "Dahouara",
            "Djeballah Khemissi",
            "El Fedjoudj",
            "Guelaat Bou Sbaa",
            "Guelma",
            "Hammam Debagh",
            "Hammam N'bail",
            "Heliopolis",
            "Houari Boumedienne",
            "Khezaras",
            "Medjez Amar",
            "Medjez Sfa",
            "Nechmaya",
            "Oued Cheham",
            "Oued Ferragha",
            "Oued Zenati",
            "Ras El Agba",
            "Roknia",
            "Sellaoua Announa",
            "Tamlouka"
        ]
    },
    {
        "id": 25,
        "code": "25",
        "name": "Constantine",
        "communes": [
            "Ain Abid",
            "Ain Smara",
            "Ben Badis",
            "Beni Hamidane",
            "Constantine",
            "Didouche Mourad",
            "El Khroub",
            "Hamma Bouziane",
            "Ibn Ziad",
            "Messaoud Boudjeriou",
            "Ouled Rahmoun",
            "Zighoud Youcef"
        ]
    },
    {
        "id": 26,
        "code": "26",
        "name": "Medea",
        "communes": [
            "Aissaouia",
            "Baata",
            "Ben Chicao",
            "Beni Slimane",
            "Berrouaghia",
            "Bir Ben Laabed",
            "Bouaichoune",
            "Bouchrahil",
            "Bouskene",
            "Djouab",
            "Draa Esmar",
            "El Azizia",
            "El Guelbelkebir",
            "El Hamdania",
            "El Haoudane",
            "El Omaria",
            "Hannacha",
            "Khams Djouamaa",
            "Maghraoua",
            "Medea",
            "Medjebar",
            "Mezerana",
            "Mihoub",
            "Ouamri",
            "Oued Harbil",
            "Ouled Bouachra",
            "Ouled Brahim",
            "Ouled Deid",
            "Ouzera",
            "Rebaia",
            "Sedraya",
            "Seghouane",
            "Si Mahdjoub",
            "Sidi Naamane",
            "Sidi Rabie",
            "Sidi Zahar",
            "Sidi Ziane",
            "Souagui",
            "Tablat",
            "Tamesguida",
            "Tizi Mahdi",
            "Tletat Ed Douair",
            "Zoubiria"
        ]
    },
    {
        "id": 27,
        "code": "27",
        "name": "Mostaganem",
        "communes": [
            "Achaacha",
            "Ain-Boudinar",
            "Ain-Nouissy",
            "Ain-Sidi Cherif",
            "Ain-Tedles",
            "Benabdelmalek Ramdane",
            "Bouguirat",
            "Fornaka",
            "Hadjadj",
            "Hassi Mameche",
            "Hassiane",
            "Khadra",
            "Kheir-Eddine",
            "Mansourah",
            "Mazagran",
            "Mesra",
            "Mostaganem",
            "Nekmaria",
            "Oued El Kheir",
            "Ouled Boughalem",
            "Ouled-Maalah",
            "Safsaf",
            "Sayada",
            "Sidi Ali",
            "Sidi Belaattar",
            "Sidi-Lakhdar",
            "Sirat",
            "Souaflia",
            "Sour",
            "Stidia",
            "Tazgait",
            "Touahria"
        ]
    },
    {
        "id": 28,
        "code": "28",
        "name": "M'Sila",
        "communes": [
            "Ain El Hadjel",
            "Ain Khadra",
            "Belaiba",
            "Beni Ilmane",
            "Berhoum",
            "Bouti Sayeh",
            "Chellal",
            "Dehahna",
            "Djebel Messaad",
            "El Houamed",
            "Hammam Dalaa",
            "Khettouti Sed-El-Jir",
            "Khoubana",
            "M'cif",
            "M'sila",
            "Magra",
            "Ouanougha",
            "Ouled Addi Guebala",
            "Ouled Derradj",
            "Ouled Madhi",
            "Ouled Mansour",
            "Sidi Aissa",
            "Souamaa",
            "Tarmount"
        ]
    },
    {
        "id": 29,
        "code": "29",
        "name": "Mascara",
        "communes": [
            "Ain Fares",
            "Ain Fekan",
            "Ain Ferah",
            "Ain Frass",
            "Alaimia",
            "Aouf",
            "Benian",
            "Bou Henni",
            "Bouhanifia",
            "Chorfa",
            "El Bordj",
            "El Gaada",
            "El Ghomri",
            "El Gueitena",
            "El Hachem",
            "El Keurt",
            "El Mamounia",
            "El Menaouer",
            "Ferraguig",
            "Froha",
            "Gharrous",
            "Ghriss",
            "Guerdjoum",
            "Hacine",
            "Khalouia",
            "Makhda",
            "Maoussa",
            "Mascara",
            "Matemore",
            "Mocta-Douz",
            "Mohammadia",
            "Nesmot",
            "Oggaz",
            "Oued El Abtal",
            "Oued Taria",
            "Ras El Ain Amirouche",
            "Sedjerara",
            "Sehailia",
            "Sidi Abdeldjebar",
            "Sidi Abdelmoumene",
            "Sidi Boussaid",
            "Sidi Kada",
            "Sig",
            "Tighennif",
            "Tizi",
            "Zahana",
            "Zelamta"
        ]
    },
    {
        "id": 30,
        "code": "30",
        "name": "Ouargla",
        "communes": [
            "Ain Beida",
            "El Borma",
            "Hassi Ben Abdellah",
            "Hassi Messaoud",
            "N'goussa",
            "Ouargla",
            "Rouissat",
            "Sidi Khouiled"
        ]
    },
    {
        "id": 31,
        "code": "31",
        "name": "Oran",
        "communes": [
            "Ain Biya",
            "Ain Kerma",
            "Ain Turk",
            "Arzew",
            "Ben Freha",
            "Bethioua",
            "Bir El Djir",
            "Boufatis",
            "Bousfer",
            "Boutlelis",
            "El Ancor",
            "El Braya",
            "El Kerma",
            "Es Senia",
            "Gdyel",
            "Hassi Ben Okba",
            "Hassi Bounif",
            "Hassi Mefsoukh",
            "Marsat El Hadjadj",
            "Mers El Kebir",
            "Messerghin",
            "Oran",
            "Oued Tlelat",
            "Sidi Ben Yebka",
            "Sidi Chami",
            "Tafraoui"
        ]
    },
    {
        "id": 32,
        "code": "32",
        "name": "El Bayadh",
        "communes": [
            "Ain El Orak",
            "Boualem",
            "Bougtoub",
            "El Bayadh",
            "El Bnoud",
            "El Kheiter",
            "El Mehara",
            "Kef El Ahmar",
            "Krakda",
            "Rogassa",
            "Sidi Ameur",
            "Sidi Slimane",
            "Sidi Tiffour",
            "Stitten",
            "Tousmouline"
        ]
    },
    {
        "id": 33,
        "code": "33",
        "name": "Illizi",
        "communes": [
            "Bordj Omar Driss",
            "Debdeb",
            "Illizi",
            "In Amenas"
        ]
    },
    {
        "id": 34,
        "code": "34",
        "name": "Bordj Bou Arreridj",
        "communes": [
            "Ain Taghrout",
            "Ain Tesra",
            "B. B. Arreridj",
            "Belimour",
            "Ben Daoud",
            "Bir Kasdali",
            "Bordj Ghedir",
            "Bordj Zemmoura",
            "Colla",
            "Djaafra",
            "El Achir",
            "El Annasseur",
            "El Euch",
            "El M'hir",
            "El Main",
            "Elhammadia",
            "Ghailasa",
            "Haraza",
            "Hasnaoua",
            "Khelil",
            "Ksour",
            "Mansoura",
            "Medjana",
            "Ouled Brahem",
            "Ouled Dahmane",
            "Ouled Sidi-Brahim",
            "Rabta",
            "Ras El Oued",
            "Sidi-Embarek",
            "Taglait",
            "Tassamert",
            "Tefreg",
            "Teniet En Nasr",
            "Tixter"
        ]
    },
    {
        "id": 35,
        "code": "35",
        "name": "Boumerdes",
        "communes": [
            "Afir",
            "Ammal",
            "Baghlia",
            "Ben Choud",
            "Beni Amrane",
            "Bordj Menaiel",
            "Boudouaou",
            "Boudouaou El Bahri",
            "Boumerdes",
            "Bouzegza Keddara",
            "Chabet El Ameur",
            "Corso",
            "Dellys",
            "Djinet",
            "El Kharrouba",
            "Hammedi",
            "Isser",
            "Khemis El Khechna",
            "Larbatache",
            "Leghata",
            "Naciria",
            "Ouled Aissa",
            "Ouled Hedadj",
            "Ouled Moussa",
            "Si Mustapha",
            "Sidi Daoud",
            "Souk El Had",
            "Taourga",
            "Thenia",
            "Tidjelabine",
            "Timezrit",
            "Zemmouri"
        ]
    },
    {
        "id": 36,
        "code": "36",
        "name": "El Tarf",
        "communes": [
            "Ain El Assel",
            "Ain Kerma",
            "Asfour",
            "Ben M Hidi",
            "Berrihane",
            "Besbes",
            "Bougous",
            "Bouhadjar",
            "Bouteldja",
            "Chebaita Mokhtar",
            "Chefia",
            "Chihani",
            "Drean",
            "Echatt",
            "El Aioun",
            "El Kala",
            "El Tarf",
            "Hammam Beni Salah",
            "Lac Des Oiseaux",
            "Oued Zitoun",
            "Raml Souk",
            "Souarekh",
            "Zerizer",
            "Zitouna"
        ]
    },
    {
        "id": 37,
        "code": "37",
        "name": "Tindouf",
        "communes": [
            "Oum El Assel",
            "Tindouf"
        ]
    },
    {
        "id": 38,
        "code": "38",
        "name": "Tissemsilt",
        "communes": [
            "Ammari",
            "Beni Chaib",
            "Beni Lahcene",
            "Bordj Bounaama",
            "Bordj El Emir Abdelkader",
            "Boucaid",
            "Khemisti",
            "Larbaa",
            "Lardjem",
            "Layoune",
            "Lazharia",
            "Maacem",
            "Melaab",
            "Ouled Bessam",
            "Sidi Abed",
            "Sidi Boutouchent",
            "Sidi Lantri",
            "Sidi Slimane",
            "Tamellahet",
            "Theniet El Had",
            "Tissemsilt",
            "Youssoufia"
        ]
    },
    {
        "id": 39,
        "code": "39",
        "name": "El Oued",
        "communes": [
            "Bayadha",
            "Ben Guecha",
            "Debila",
            "Douar El Maa",
            "El Ogla",
            "El-Oued",
            "Guemar",
            "Hamraia",
            "Hassani Abdelkrim",
            "Hassi Khalifa",
            "Kouinine",
            "Magrane",
            "Mih Ouansa",
            "Nakhla",
            "Oued El Alenda",
            "Ourmes",
            "Reguiba",
            "Robbah",
            "Sidi Aoun",
            "Taghzout",
            "Taleb Larbi",
            "Trifaoui"
        ]
    },
    {
        "id": 40,
        "code": "40",
        "name": "Khenchela",
        "communes": [
            "Ain Touila",
            "Babar",
            "Baghai",
            "Bouhmama",
            "Chechar",
            "Chelia",
            "Djellal",
            "El Hamma",
            "El Mahmal",
            "El Oueldja",
            "Ensigha",
            "Kais",
            "Khenchela",
            "Khirane",
            "M'sara",
            "M'toussa",
            "Ouled Rechache",
            "Remila",
            "Tamza",
            "Taouzianat",
            "Yabous"
        ]
    },
    {
        "id": 41,
        "code": "41",
        "name": "Souk Ahras",
        "communes": [
            "Ain Soltane",
            "Ain Zana",
            "Bir Bouhouche",
            "Drea",
            "Haddada",
            "Hanencha",
            "Khedara",
            "Khemissa",
            "M'daourouche",
            "Machroha",
            "Merahna",
            "Oued Kebrit",
            "Ouillen",
            "Ouled Driss",
            "Ouled Moumen",
            "Oum El Adhaim",
            "Ragouba",
            "Safel El Ouiden",
            "Sedrata",
            "Sidi Fredj",
            "Souk Ahras",
            "Taoura",
            "Terraguelt",
            "Tiffech",
            "Zaarouria",
            "Zouabi"
        ]
    },
    {
        "id": 42,
        "code": "42",
        "name": "Tipaza",
        "communes": [
            "Aghbal",
            "Ahmer El Ain",
            "Ain Tagourait",
            "Attatba",
            "Beni Mileuk",
            "Bou Haroun",
            "Bou Ismail",
            "Bourkika",
            "Chaiba",
            "Cherchell",
            "Damous",
            "Douaouda",
            "Fouka",
            "Gouraya",
            "Hadjout",
            "Hadjret Ennous",
            "Khemisti",
            "Kolea",
            "Larhat",
            "Menaceur",
            "Merad",
            "Messelmoun",
            "Nador",
            "Sidi Ghiles",
            "Sidi Rached",
            "Sidi Semiane",
            "Sidi-Amar",
            "Tipaza"
        ]
    },
    {
        "id": 43,
        "code": "43",
        "name": "Mila",
        "communes": [
            "Ahmed Rachedi",
            "Ain Beida Harriche",
            "Ain Mellouk",
            "Ain Tine",
            "Amira Arres",
            "Benyahia Abderrahmane",
            "Bouhatem",
            "Chelghoum Laid",
            "Chigara",
            "Derrahi Bousselah",
            "El Ayadi Barbes",
            "El Mechira",
            "Ferdjioua",
            "Grarem Gouga",
            "Hamala",
            "Mila",
            "Minar Zarza",
            "Oued Athmenia",
            "Oued Endja",
            "Oued Seguen",
            "Ouled Khalouf",
            "Rouached",
            "Sidi Khelifa",
            "Sidi Merouane",
            "Tadjenanet",
            "Tassadane Haddada",
            "Tassala Lematai",
            "Teleghma",
            "Terrai Bainen",
            "Tiberguent",
            "Yahia Beniguecha",
            "Zeghaia"
        ]
    },
    {
        "id": 44,
        "code": "44",
        "name": "Ain Defla",
        "communes": [
            "Ain-Benian",
            "Ain-Bouyahia",
            "Ain-Defla",
            "Ain-Lechiakh",
            "Ain-Soltane",
            "Ain-Torki",
            "Arib",
            "Bathia",
            "Belaas",
            "Ben Allal",
            "Bir-Ould-Khelifa",
            "Birbouche",
            "Bordj-Emir-Khaled",
            "Boumedfaa",
            "Bourached",
            "Djelida",
            "Djemaa Ouled Cheikh",
            "Djendel",
            "El-Abadia",
            "El-Amra",
            "El-Attaf",
            "El-Maine",
            "Hammam-Righa",
            "Hassania",
            "Hoceinia",
            "Khemis-Miliana",
            "Mekhatria",
            "Miliana",
            "Oued Chorfa",
            "Oued Djemaa",
            "Rouina",
            "Sidi-Lakhdar",
            "Tacheta Zegagha",
            "Tarik-Ibn-Ziad",
            "Tiberkanine",
            "Zeddine"
        ]
    },
    {
        "id": 45,
        "code": "45",
        "name": "Naama",
        "communes": [
            "Ain Ben Khelil",
            "Ain Sefra",
            "Asla",
            "Djenienne Bourezg",
            "El Biodh",
            "Kasdir",
            "Makmen Ben Amar",
            "Mecheria",
            "Moghrar",
            "Naama",
            "Sfissifa",
            "Tiout"
        ]
    },
    {
        "id": 46,
        "code": "46",
        "name": "Ain Temouchent",
        "communes": [
            "Aghlal",
            "Ain El Arbaa",
            "Ain Kihal",
            "Ain Temouchent",
            "Ain Tolba",
            "Aoubellil",
            "Beni Saf",
            "Bouzedjar",
            "Chaabat El Ham",
            "Chentouf",
            "El Amria",
            "El Maleh",
            "El Messaid",
            "Emir Abdelkader",
            "Hammam Bou Hadjar",
            "Hassasna",
            "Hassi El Ghella",
            "Oued Berkeche",
            "Oued Sebbah",
            "Ouled Boudjemaa",
            "Ouled Kihal",
            "Oulhaca El Gheraba",
            "Sidi Ben Adda",
            "Sidi Boumediene",
            "Sidi Ouriache",
            "Sidi Safi",
            "Tamzoura",
            "Terga"
        ]
    },
    {
        "id": 47,
        "code": "47",
        "name": "Ghardaia",
        "communes": [
            "Berriane",
            "Bounoura",
            "Dhayet Bendhahoua",
            "El Atteuf",
            "El Guerrara",
            "Ghardaia",
            "Mansoura",
            "Metlili",
            "Sebseb",
            "Zelfana"
        ]
    },
    {
        "id": 48,
        "code": "48",
        "name": "Relizane",
        "communes": [
            "Ain Rahma",
            "Ain-Tarek",
            "Ammi Moussa",
            "Belaassel Bouzagza",
            "Bendaoud",
            "Beni Dergoun",
            "Beni Zentis",
            "Dar Ben Abdelah",
            "Djidiouia",
            "El H'madna",
            "El Hassi",
            "El Ouldja",
            "El-Guettar",
            "El-Matmar",
            "Had Echkalla",
            "Hamri",
            "Kalaa",
            "Lahlef",
            "Mazouna",
            "Mediouna",
            "Mendes",
            "Merdja Sidi Abed",
            "Ouarizane",
            "Oued El Djemaa",
            "Oued Essalem",
            "Oued-Rhiou",
            "Ouled Aiche",
            "Ouled Sidi Mihoub",
            "Ramka",
            "Relizane",
            "Sidi Khettab",
            "Sidi Lazreg",
            "Sidi M'hamed Benali",
            "Sidi M'hamed Benaouda",
            "Sidi Saada",
            "Souk El Had",
            "Yellel",
            "Zemmoura"
        ]
    },
    {
        "id": 49,
        "code": "49",
        "name": "Timimoun",
        "communes": [
            "Aougrout",
            "Charouine",
            "Deldoul",
            "Ksar Kaddour",
            "Metarfa",
            "Ouled Aissa",
            "Ouled Said",
            "Talmine",
            "Timimoun",
            "Tinerkouk"
        ]
    },
    {
        "id": 50,
        "code": "50",
        "name": "Bordj Badji Mokhtar",
        "communes": [
            "Bordj Badji Mokhtar",
            "Timiaouine"
        ]
    },
    {
        "id": 51,
        "code": "51",
        "name": "Ouled Djellal",
        "communes": [
            "Besbes",
            "Chaiba",
            "Doucen",
            "Ouled Djellal",
            "Ras El Miad",
            "Sidi Khaled"
        ]
    },
    {
        "id": 52,
        "code": "52",
        "name": "Beni Abbes",
        "communes": [
            "Beni-Abbes",
            "Beni-Ikhlef",
            "El Ouata",
            "Igli",
            "Kerzaz",
            "Ksabi",
            "Ouled-Khodeir",
            "Tamtert",
            "Timoudi"
        ]
    },
    {
        "id": 53,
        "code": "53",
        "name": "In Salah",
        "communes": [
            "Ain Salah",
            "Foggaret Ezzoua",
            "Inghar"
        ]
    },
    {
        "id": 54,
        "code": "54",
        "name": "In Guezzam",
        "communes": [
            "Ain Guezzam",
            "Tin Zouatine"
        ]
    },
    {
        "id": 55,
        "code": "55",
        "name": "Touggourt",
        "communes": [
            "Benaceur",
            "Blidet Amor",
            "El Alia",
            "El-Hadjira",
            "M'naguer",
            "Megarine",
            "Nezla",
            "Sidi Slimane",
            "Taibet",
            "Tebesbest",
            "Temacine",
            "Touggourt",
            "Zaouia El Abidia"
        ]
    },
    {
        "id": 56,
        "code": "56",
        "name": "Djanet",
        "communes": [
            "Bordj El Haouass",
            "Djanet"
        ]
    },
    {
        "id": 57,
        "code": "57",
        "name": "El M'Ghair",
        "communes": [
            "Djamaa",
            "El-M'ghaier",
            "M'rara",
            "Oum Touyour",
            "Sidi Amrane",
            "Sidi Khelil",
            "Still",
            "Tenedla"
        ]
    },
    {
        "id": 58,
        "code": "58",
        "name": "El Meniaa",
        "communes": [
            "El Meniaa",
            "Hassi Fehal",
            "Hassi Gara"
        ]
    },
    {
        "id": 59,
        "code": "59",
        "name": "Aflou",
        "communes": [
            "Aflou",
            "Ain Sidi Ali",
            "Brida",
            "El Beidha",
            "El Ghicha",
            "Gueltat Sidi Saad",
            "Hadj Mechri",
            "Oued M'zi",
            "Oued Morra",
            "Sebgag",
            "Sidi Bouzid",
            "Taouiala"
        ]
    },
    {
        "id": 60,
        "code": "60",
        "name": "El Abiodh Sidi Cheikh",
        "communes": [
            "Arbaouat",
            "Boussemghoun",
            "Brezina",
            "Cheguig",
            "Chellala",
            "Ghassoul",
            "Labiodh Sidi Cheikh"
        ]
    },
    {
        "id": 61,
        "code": "61",
        "name": "El Aricha",
        "communes": [
            "Bouihi",
            "El Aricha",
            "El Gor",
            "Sidi Djillali"
        ]
    },
    {
        "id": 62,
        "code": "62",
        "name": "El Kantara",
        "communes": [
            "Ain Zaatout",
            "Branis",
            "Djemorah",
            "El Kantara",
            "El Outaya"
        ]
    },
    {
        "id": 63,
        "code": "63",
        "name": "Barika",
        "communes": [
            "Azil Abedelkader",
            "Barika",
            "Bitam",
            "Djezzar",
            "M Doukal",
            "Ouled Ammar",
            "Seggana",
            "Tilatou"
        ]
    },
    {
        "id": 64,
        "code": "64",
        "name": "Bou Saada",
        "communes": [
            "Ain El Melh",
            "Ain Fares",
            "Ain Rich",
            "Ben Srour",
            "Benzouh",
            "Bir Foda",
            "Bou Saada",
            "El Hamel",
            "M'tarfa",
            "Maadid",
            "Maarif",
            "Medjedel",
            "Menaa",
            "Mohamed Boudiaf",
            "Ouled Sidi Brahim",
            "Ouled Slimane",
            "Oulteme",
            "Sidi Ameur",
            "Sidi Hadjeres",
            "Sidi M'hamed",
            "Slim",
            "Tamsa",
            "Zarzour"
        ]
    },
    {
        "id": 65,
        "code": "65",
        "name": "Bir El Ater",
        "communes": [
            "Bir-El-Ater",
            "El Ogla El Malha",
            "Ferkane",
            "Negrine"
        ]
    },
    {
        "id": 66,
        "code": "66",
        "name": "Ksar El Boukhari",
        "communes": [
            "Ain Boucif",
            "Ain Ouksir",
            "Aziz",
            "Boghar",
            "Bouaiche",
            "Boughzoul",
            "Chabounia",
            "Chelalet El Adhaoura",
            "Cheniguel",
            "Derrag",
            "El Ouinet",
            "Kef Lakhdar",
            "Ksar El Boukhari",
            "M'fatha",
            "Ouled Antar",
            "Ouled Emaaraf",
            "Ouled Hellal",
            "Oum El Djellil",
            "Saneg",
            "Sidi Demed",
            "Tafraout"
        ]
    },
    {
        "id": 67,
        "code": "67",
        "name": "Ksar Chellala",
        "communes": [
            "Bougara",
            "Hamadia",
            "Ksar Chellala",
            "Rechaiga",
            "Serghine",
            "Zmalet El Emir Abdelkade"
        ]
    },
    {
        "id": 68,
        "code": "68",
        "name": "Ain Oussara",
        "communes": [
            "Ain Fekka",
            "Ain Oussera",
            "Benhar",
            "Birine",
            "Bouira Lahdab",
            "El Khemis",
            "Guernini",
            "Had Sahary",
            "Hassi Fedoul",
            "Sidi Laadjel"
        ]
    },
    {
        "id": 69,
        "code": "69",
        "name": "Messaad",
        "communes": [
            "Amourah",
            "Deldoul",
            "Faidh El Botma",
            "Guettara",
            "Messaad",
            "Oum Laadham",
            "Sed Rahal",
            "Selmana"
        ]
    }
];

  const ALGERIA_DATA = {
    getWilayas: function() {
      return algeriaData.map(w => ({ id: w.id, code: w.code, name: w.name }));
    },
    getWilayaById: function(id) {
      const numericId = parseInt(id, 10);
      return algeriaData.find(w => w.id === numericId) || null;
    },
    getCommunes: function(wilayaIdOrCode) {
      const numericId = parseInt(wilayaIdOrCode, 10);
      const wilaya = algeriaData.find(w => w.id === numericId || parseInt(w.code, 10) === numericId);
      return wilaya ? wilaya.communes : [];
    }
  };
  window.ALGERIA_DATA = ALGERIA_DATA;
})(window);